-- FairLens baseline schema for Supabase Postgres.
-- Apply with: supabase db push

create extension if not exists "pgcrypto";

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  avg_monthly_inflow double precision not null,
  inflow_volatility double precision not null,
  avg_monthly_outflow double precision not null,
  min_balance_30d double precision not null,
  neg_balance_days_30d integer not null,
  purchase_to_inflow_ratio double precision not null,
  total_burden_ratio double precision not null,
  buffer_ratio double precision not null,
  stress_index double precision not null,
  risk_probability double precision not null,
  decision text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_transactions_risk_probability
  on public.transactions (risk_probability);
create index if not exists idx_transactions_decision
  on public.transactions (decision);
create index if not exists idx_transactions_created_at
  on public.transactions (created_at desc);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor text not null,
  action text not null,
  details text not null,
  status text not null,
  entity_id text,
  source text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_audit_logs_status
  on public.audit_logs (status);
create index if not exists idx_audit_logs_actor
  on public.audit_logs (actor);
create index if not exists idx_audit_logs_entity_id
  on public.audit_logs (entity_id);
create index if not exists idx_audit_logs_created_at
  on public.audit_logs (created_at desc);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'admin')),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.transactions enable row level security;
alter table public.audit_logs enable row level security;
alter table public.user_roles enable row level security;

drop policy if exists "service_role_transactions_all" on public.transactions;
create policy "service_role_transactions_all"
  on public.transactions
  for all
  to service_role
  using (true)
  with check (true);

drop policy if exists "service_role_audit_logs_all" on public.audit_logs;
create policy "service_role_audit_logs_all"
  on public.audit_logs
  for all
  to service_role
  using (true)
  with check (true);

drop policy if exists "service_role_user_roles_all" on public.user_roles;
create policy "service_role_user_roles_all"
  on public.user_roles
  for all
  to service_role
  using (true)
  with check (true);

drop policy if exists "users_read_own_role" on public.user_roles;
create policy "users_read_own_role"
  on public.user_roles
  for select
  to authenticated
  using (auth.uid() = user_id);

